version: "3.9"
services:
  app:
    container_name: python3_geosearch
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - "redis"
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis

  redis:
    container_name: redis62_geosearch
    image: "redis:6.2.1-alpine"
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
